### ISSUE TITLE
Switch mappings to brain regions to pull from assertions based on MERFISH data

### ISSUE THREAD

**Issue by dosumis** [Cellular-Semantics/whole_mouse_brain_ontology#11]
The cluster table in this spreadsheet: https://static-content.springer.com/esm/art%3A10.1038%2Fs41586-023-06812-z/MediaObjects/41586_2023_6812_MOESM8_ESM.xlsx

Has two columns mapping to MBA brain regions based on MerFish data - one a broad mapping (CCF_broad.freq), one a specific mapping (CCF_acronym.freq)

CCF_broad.freq | CCF_acronym.freq
|:----------------|:-------------------------------- |
Isocortex:0.57,CTXsp:0.21,OLF:0.2 | EPd:0.11,OLF:0.11,SSs6a:0.1,CLA:0.09,PIR:0.09,AId6a:0.07,MOp6a:0.06,GU6a:0.06,AIv5:0.04,VISC6a:0.03,SSp-m6a:0.03,AIv6a:0.02
Isocortex:0.64,CTXsp:0.24 | CLA:0.12,EPd:0.1,GU6a:0.07,SSs6a:0.06,VISC6a:0.06,TEa6a:0.06,TEa5:0.05,AId6a:0.05,AIp6a:0.05,ECT6a:0.03,ECT5:0.03,ee:0.02,ENTl6a:0.02,AUDv5:0.02,scwm:0.02,ENTl5:0.01,AUDv6a:0.01,SSs6b:0.01

Explanation of content: 

CCF_broad.freq | Distribution of CCF broad regions based   on CCF registration. Formatted as CCF broad region followed by the fraction   of mapped MERFISH cells registered to the given region, sorted from highest   to lowest till 80% cells are covered
-- | --
CCF_acronym.freq | Distribution of finer CCF structures based on CCF registration. Formatted   as CCF structures followed by the fraction of mapped MERFISH cells registered   to the given structure, sorted from highest to lowest till 80% cells are   covered

I think it will be useful to make soma_location axioms for both.  The edge should have the percent cells mapped.  It should also have a record of the assay used - EFO:0008992 MerFish.  I suggest 'assay_label' for the name  'assay': for the ID.

Open question:  Should we impose a cuttoff for percent cells?

**Comment by hkir-dev** [comment]
Two new APs added:
- Annotation Property: <http://purl.obolibrary.org/obo/PCL_0010065> (cell_ratio)
- Annotation Property: <http://purl.obolibrary.org/obo/PCL_0010064> (assay_label)

`cell_ratio > 0.05` threshold applied to keep template file manageable. Now has max 14 MBA terms for a cluster.

```owl
# Class: <http://purl.obolibrary.org/obo/PCL_0112412> (0032 L5/6 IT TPE-ENT Glut_6 intratelencephalic-projecting glutamatergic cortical neuron (Mmus))

AnnotationAssertion(<http://purl.obolibrary.org/obo/IAO_0000028> <http://purl.obolibrary.org/obo/PCL_0112412> "0032 L5/6 IT TPE-ENT Glut_6 (Mouse)"^^xsd:string)
AnnotationAssertion(<http://purl.obolibrary.org/obo/IAO_0000115> <http://purl.obolibrary.org/obo/PCL_0112412> "A intratelencephalic-projecting glutamatergic cortical neuron of the Mus musculus brain. The soma of these cells can be found in the Retrohippocampal region. The reference data for this cell type is CS20230722_CLUS_0032."^^xsd:string)
AnnotationAssertion(Annotation(<http://purl.obolibrary.org/obo/PCL_0010064> <http://www.ebi.ac.uk/efo/EFO_0008992>) Annotation(<http://purl.obolibrary.org/obo/PCL_0010065> "0.38"^^xsd:string) Annotation(rdfs:comment "Location assignment based on CCF acronym region."^^xsd:string) <http://purl.obolibrary.org/obo/PCL_0010063> <http://purl.obolibrary.org/obo/PCL_0112412> <https://purl.brain-bican.org/ontology/mbao/MBA_1084>)
AnnotationAssertion(Annotation(<http://purl.obolibrary.org/obo/PCL_0010064> <http://www.ebi.ac.uk/efo/EFO_0008992>) Annotation(<http://purl.obolibrary.org/obo/PCL_0010065> "0.15"^^xsd:string) Annotation(rdfs:comment "Location assignment based on CCF acronym region."^^xsd:string) <http://purl.obolibrary.org/obo/PCL_0010063> <http://purl.obolibrary.org/obo/PCL_0112412> <https://purl.brain-bican.org/ontology/mbao/MBA_502>)
AnnotationAssertion(Annotation(<http://purl.obolibrary.org/obo/PCL_0010064> <http://www.ebi.ac.uk/efo/EFO_0008992>) Annotation(<http://purl.obolibrary.org/obo/PCL_0010065> "1.0"^^xsd:string) Annotation(rdfs:comment "Location assignment based on CCF broad region."^^xsd:string) <http://purl.obolibrary.org/obo/PCL_0010063> <http://purl.obolibrary.org/obo/PCL_0112412> <https://purl.brain-bican.org/ontology/mbao/MBA_822>)
AnnotationAssertion(Annotation(<http://purl.obolibrary.org/obo/PCL_0010064> <http://www.ebi.ac.uk/efo/EFO_0008992>) Annotation(<http://purl.obolibrary.org/obo/PCL_0010065> "0.38"^^xsd:string) Annotation(rdfs:comment "Location assignment based on CCF acronym region."^^xsd:string) <http://purl.obolibrary.org/obo/PCL_0010063> <http://purl.obolibrary.org/obo/PCL_0112412> <https://purl.brain-bican.org/ontology/mbao/MBA_843>)
```

release blocked by https://github.com/brain-bican/mouse_brain_atlas_ontology/issues/2

**Comment by dosumis** [comment]
I think that's reasonable, and consistent with Hongkui's suggestions on the call.

**Comment by dosumis** [comment]
For APs  - we should align AP for what you're calling cell ratio with what Ugur is using on in the KG linking to tissue, stage etc.  We need something like 'percent cells' or 'fraction of cells'.  It shouldn't really be in PCL in the long term. 

Thinking about it, we can probably do better for assay too & also align that with the KG.

**Comment by hkir-dev** [comment]
TODO: fix datatype in postprocess
https://github.com/obophenotype/cell-ontology/blob/master/src/sparql/replace_string_to_datetime.ru

**Comment by hkir-dev** [comment]
data type fix implemented https://github.com/Cellular-Semantics/whole_mouse_brain_ontology/blob/version2/src/sparql/replace_string_to_float.ru
