### ISSUE TITLE
Add characterising marker set - combo markers from paper

### ISSUE THREAD

**Issue by dosumis** [Cellular-Semantics/whole_mouse_brain_ontology#19]
author category: labelset.markers.combo

e.g. 

cluster.markers.combo | 
-- | 
Car3,Satb2,Lgr5 | 
Car3,Slc17a7,4930407I19Rik | 
Car3,Satb2,Ccbe1 |

supertype.markers.combo 
-- |
Car3,Nrg3,Gm34567
Ccnb1,Tcf7l1
Osr1,Satb2,Gpr88,Ccdc80,Lhfp

Ideally we would add some details of how these were derived to the marker set node (I haven't been able to work that out yet from the paper)

**Comment by dosumis** [comment]
For schema follow schema used for NS-Forest - using has_characterising_marker_set .  In this case we (currently) have no confidence score or assay details.

**Comment by dosumis** [comment]
Maker sets still say NS-Forest.

**Comment by hkir-dev** [comment]
Fixed
